stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  REGISTRY_IMAGE: "registry.gitlab.com/jes11sy-group/backend"
  PRODUCTION_HOST: "176.124.200.32"
  PRODUCTION_USER: "root"

# Кеширование для ускорения сборки
cache:
  paths:
    - .pytest_cache/
    - __pycache__/

# Тестирование временно отключено

# Проверка безопасности временно отключена

# Сборка Docker образов
build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "🏗️ Сборка Docker образа..."
    - docker build -t $REGISTRY_IMAGE/backend:$CI_COMMIT_SHA -f deployment/Dockerfile.production .
    - docker build -t $REGISTRY_IMAGE/backend:latest -f deployment/Dockerfile.production .
    - echo "📤 Загрузка образа в registry..."
    - docker push $REGISTRY_IMAGE/backend:$CI_COMMIT_SHA
    - docker push $REGISTRY_IMAGE/backend:latest
    - echo "✅ Образ собран и загружен"
  only:
    - main

# Деплой на staging
deploy_staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash curl
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_PRIVATE_KEY" > /tmp/ssh_key
    - chmod 600 /tmp/ssh_key
    - ssh-add /tmp/ssh_key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $STAGING_HOST >> ~/.ssh/known_hosts
  script:
    - echo "🚀 Деплой на staging сервер..."
    - ssh $STAGING_USER@$STAGING_HOST "
        cd /opt/backend &&
        docker-compose -f docker-compose.staging.yml pull &&
        docker-compose -f docker-compose.staging.yml up -d &&
        docker system prune -f
      "
    - echo "✅ Staging деплой завершен"
  environment:
    name: staging
    url: https://staging-api.lead-schem.ru
  only:
    - develop

# Деплой на продакшен
deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash curl git
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" > /tmp/ssh_key
    - chmod 600 /tmp/ssh_key
    - ssh-add /tmp/ssh_key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $PRODUCTION_HOST >> ~/.ssh/known_hosts
  script:
    - echo "🚀 Деплой на продакшен сервер..."
    - |
      ssh $PRODUCTION_USER@$PRODUCTION_HOST "
        cd /home/deployer/backend-api &&
        git remote set-url origin https://gitlab-ci-token:$GITLAB_TOKEN@gitlab.com/jes11sy-group/backend.git &&
        git pull origin main &&

        echo '📝 Создание .env файла...' &&
        cat > .env << EOF
      # Database Configuration
      POSTGRESQL_HOST=${POSTGRESQL_HOST}
      POSTGRESQL_PORT=${POSTGRESQL_PORT}
      POSTGRESQL_USER=${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      POSTGRESQL_DBNAME=${POSTGRESQL_DBNAME}

      # Security
      SECRET_KEY=${SECRET_KEY}
      JWT_SECRET_KEY=${JWT_SECRET_KEY}

      # Redis
      REDIS_PASSWORD=${REDIS_PASSWORD}

      # SSL and Domain
      LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}

      # Traefik
      TRAEFIK_AUTH=${TRAEFIK_AUTH}

      # Monitoring
      GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

      # Environment
      ENVIRONMENT=production
      DEBUG=false
      EOF

        echo '📝 Создание конфигурации Prometheus...' &&
        mkdir -p deployment/monitoring/prometheus_config &&
        cat > deployment/monitoring/prometheus_config/prometheus.yml << 'PROMETHEUS_EOF'
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      rule_files:

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']

        - job_name: 'backend'
          static_configs:
            - targets: ['backend:8000']
          metrics_path: '/metrics'

        - job_name: 'traefik'
          static_configs:
            - targets: ['traefik:8080']
      PROMETHEUS_EOF

        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin &&
        docker-compose -f deployment/docker-compose.production.yml build --no-cache &&
        docker-compose -f deployment/docker-compose.production.yml up -d &&
        docker system prune -f &&
        echo '✅ Продакшен деплой завершен'
      "
    - rm -f /tmp/ssh_key
    - echo "🎉 Сервис успешно развернут!"
  environment:
    name: production
    url: http://176.124.200.32:8000
  only:
    - main

# Откат в случае проблем
rollback_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$PRODUCTION_SSH_PRIVATE_KEY" > /tmp/ssh_key
    - chmod 600 /tmp/ssh_key
    - ssh-add /tmp/ssh_key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $PRODUCTION_HOST >> ~/.ssh/known_hosts
  script:
    - echo "🔄 Откат к предыдущей версии..."
    - ssh $PRODUCTION_USER@$PRODUCTION_HOST "
        cd /opt/backend &&
        docker-compose -f docker-compose.production.yml down &&
        docker tag $REGISTRY_IMAGE/backend:previous $REGISTRY_IMAGE/backend:latest &&
        docker-compose -f docker-compose.production.yml up -d &&
        echo '✅ Откат завершен'
      "
  environment:
    name: production
    url: https://api.lead-schem.ru
  when: manual
  only:
    - main

# Уведомления в Telegram
notify_success:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - |
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
        -H "Content-Type: application/json" \
        -d "{
          \"chat_id\": \"$TELEGRAM_CHAT_ID\",
          \"text\": \"✅ Деплой успешно завершен!\n\n🚀 Commit: $CI_COMMIT_SHA\n📝 Message: $CI_COMMIT_MESSAGE\n🌐 URL: https://api.lead-schem.ru\n⏰ Time: $(date)\",
          \"parse_mode\": \"HTML\"
        }"
  when: on_success
  only:
    - main

notify_failure:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - |
      curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
        -H "Content-Type: application/json" \
        -d "{
          \"chat_id\": \"$TELEGRAM_CHAT_ID\",
          \"text\": \"❌ Ошибка деплоя!\n\n🚀 Commit: $CI_COMMIT_SHA\n📝 Message: $CI_COMMIT_MESSAGE\n🔗 Pipeline: $CI_PIPELINE_URL\n⏰ Time: $(date)\",
          \"parse_mode\": \"HTML\"
        }"
  when: on_failure
  only:
    - main 